TYPO3:
  TYPO3CR:
    contentDimensions:
      'language':
        label: 'TYPO3.NeosDemoTypo3Org:Main:contentDimensions.language'
        icon: 'icon-language'
        default: 'en_US'
        defaultPreset: 'en_US'
        presets:
          'all': ~
          'en_US':
            label: 'English (US)'
            values: ['en_US']
            uriSegment: 'en'
          'en_UK':
            label: 'English (UK)'
            values: ['en_UK', 'en_US']
            uriSegment: 'uk'
          'de':
            label: 'German'
            values: ['de']
            uriSegment: 'de'
          'fr':
            label: 'French'
            values: ['fr']
            uriSegment: 'fr'
          'nl':
            label: 'Dutch'
            values: ['nl', 'de']
            uriSegment: 'nl'
          'da':
            label: 'Danish'
            values: ['da']
            uriSegment: 'da'
          'lv':
            label: 'Latvian'
            values: ['lv']
            uriSegment: 'lv'
